### ISSUE TITLE
Setting puppet::params via hiera does not impact settings

### ISSUE THREAD

**Issue by shishirsharma** [stephenrjohnson/puppetmodule#105]
I am using hiera.yaml 
```
puppet::params:
  parser: 'future'
```
also I have this in my profile server.pp
```
class site::profiles::puppet::server {
  contain puppet::master
}
```
This does not change parser setting, In fact i can't change any settings via hiera. I have verified my settings. And they are working for other modules.

**Comment by shishirsharma** [comment]
Actually What I am asking is that Your modules does not support hiera.

**Comment by stephenrjohnson** [comment]
You hiera key is totally wrong it should be

puppet::params::parser: 'future'
