### ISSUE TITLE
apache2 fails to start on Ubuntu 14 with passenger defaults

### ISSUE THREAD

**Issue by jerearista** [stephenrjohnson/puppetmodule#113]
After pulling the master branch today (at ccb91eaa5e1c252e350b9d484003c09ca38fc06e) I hit an issue with the passenger config in apache2 on Ubuntu 14.04. The culprit seems to be passenger_high_performance defaulting to 'true' instead of 'on'.

    apache2 -t
    AH00526: Syntax error on line 6 of /etc/apache2/mods-enabled/passenger.conf:
    PassengerHighPerformance must be On or Off

    apache2 -v
    Server version: Apache/2.4.7 (Ubuntu)
    Server built:   Apr  3 2014 12:20:28

    cat /etc/issue
    Ubuntu 14.04 LTS \n \l
    cat /etc/debian_version 
    jessie/sid

The following work-around can be used:

    class { '::puppet::master':
      # ...
      passenger_high_performance => on,                                                     
    }

I have not checked other OSes or apache/passenger versions, at this time to see if 'true' works elsewhere.    Its also possible that the "right" fix may be for the apache module to normalize true => on, false => off, etc.  I opened the issue here, however, due to the recent PR on the subject.

**Comment by stephenrjohnson** [comment]
I've just changed the default to be on.
