### ISSUE TITLE
Release to Puppet Forge

### ISSUE THREAD

**Issue by djjudas21** [stephenrjohnson/puppetmodule#114]
At my site, I'm currently only able to use Puppet modules in production which have been installed from Puppet Forge. As of today, the latest release (Dec 2014) is 72 commits behind `HEAD`. Please could you roll a release some time soon so I can use these new features (particularly the Passenger tuning). Thanks.

**Comment by dhoppe** [comment]
+1

**Comment by stephenrjohnson** [comment]
Done
