### ISSUE TITLE
module fails to generate proper SSL CA files if building from scratch

### ISSUE THREAD

**Issue by Hefeweizen** [stephenrjohnson/puppetmodule#81]
* test environment:
  * a vm running CentOS 6.5 and open-source puppet 3.7.3.
* to recreate:
  * install only puppet client; have its manifest set to install puppet server.  RPM installs, apache is configured, but apache fails to start because of missing files in SSL specification.
* tmp fix:
  * start webrick puppetmaster with 'service puppetmaster start' and then stop it.  Start apache and now everything comes up just fine.

**Comment by stephenrjohnson** [comment]
I've just added some acceptance tests and it's working fine and I can't recreate the problem.
